# Generated by Django 4.2.16 on 2024-10-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedCSVCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='')),
                ('csv_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computed_csv_calculation', to='compute.usercsvprovidedfile')),
            ],
        ),
    ]
